#!/bin/sh

while ! mount | grep -q "/export/apps"; do
    sleep 1
done

/export/apps/src/nvidia_drivers/NVIDIA-Linux-x86_64-470.223.02.run --disable-nouveau --silent --run-nvidia-xconfig --no-drm --ui=none --accept-license
/usr/bin/nvidia-smi -c 3
